# Copyright 2025 Cocotec Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Formatting support for Coco packages."""

load(
    "//coco/private:coco.bzl",
    "COCO_TOOLCHAIN_TYPE",
    "CocoPackageInfo",
    "LICENSE_ATTRIBUTES",
    "WINDOWS_CONSTRAINT_ATTR",
    "coco_runfiles",
    "create_coco_wrapper_script",
)

def _coco_fmt_test_impl(ctx):
    """Implementation for coco_fmt_test rule.

    Creates a test that runs 'popili format --verify' to check if Coco code
    is properly formatted. The test passes if code is formatted correctly,
    and fails if formatting changes are needed.
    """
    arguments = [
        "format",
        "--verify",
    ]

    wrapper_script = create_coco_wrapper_script(ctx, ctx.attr.package, arguments)

    return DefaultInfo(
        executable = wrapper_script,
        runfiles = ctx.runfiles(transitive_files = coco_runfiles(ctx, ctx.attr.package, True)),
    )

_coco_fmt_test = rule(
    implementation = _coco_fmt_test_impl,
    attrs = dict(LICENSE_ATTRIBUTES.items() + {
        "package": attr.label(
            providers = [CocoPackageInfo],
            mandatory = True,
            doc = "The coco_package target to check formatting for",
        ),
        "_windows_constraint": WINDOWS_CONSTRAINT_ATTR,
    }.items()),
    doc = """Test rule that verifies Coco code formatting.

This rule creates a test target that runs `popili format --verify` on the
specified coco_package. The test passes if all Coco source files are properly
formatted according to the formatting settings in the package's Coco.toml file.

Example:
    ```python
    coco_package(
        name = "my_pkg",
        package = "Coco.toml",
        srcs = glob(["src/**/*.coco"]),
    )

    coco_fmt_test(
        name = "my_pkg_fmt_test",
        package = ":my_pkg",
    )
    ```

To skip this test for specific targets, use standard Bazel tags:
    ```python
    coco_fmt_test(
        name = "generated_fmt_test",
        package = ":generated_pkg",
        tags = ["manual"],  # Only run when explicitly requested
    )
    ```
""",
    test = True,
    toolchains = [
        COCO_TOOLCHAIN_TYPE,
    ],
)

def _coco_fmt_binary_impl(ctx):
    """Implementation for coco_fmt_binary rule.

    Creates an executable that runs 'popili format' to format Coco code.
    """
    arguments = [
        "format",
    ]

    wrapper_script = create_coco_wrapper_script(ctx, ctx.attr.package, arguments)

    return DefaultInfo(
        executable = wrapper_script,
        runfiles = ctx.runfiles(transitive_files = coco_runfiles(ctx, ctx.attr.package, True)),
    )

_coco_fmt_binary = rule(
    implementation = _coco_fmt_binary_impl,
    attrs = dict(LICENSE_ATTRIBUTES.items() + {
        "package": attr.label(
            providers = [CocoPackageInfo],
            mandatory = True,
            doc = "The coco_package target to format",
        ),
        "_windows_constraint": WINDOWS_CONSTRAINT_ATTR,
    }.items()),
    doc = """Binary rule that formats Coco code.

This rule creates an executable target that runs `popili format` on the
specified coco_package, automatically formatting all Coco source files
according to the formatting settings in the package's Coco.toml file.

This target is typically auto-generated by coco_fmt_test and should not
be used directly.
""",
    executable = True,
    toolchains = [
        COCO_TOOLCHAIN_TYPE,
    ],
)

def _coco_fmt_test_macro_impl(name, visibility, package, **kwargs):
    # Test target (the macro's primary target); test attrs flow through kwargs.
    _coco_fmt_test(
        name = name,
        package = package,
        visibility = visibility,
        **kwargs
    )

    # Companion `bazel run` formatter. Named "<name>.format" because symbolic-macro
    # naming requires the macro-name prefix; only non-test attrs are forwarded.
    _coco_fmt_binary(
        name = name + ".format",
        package = package,
        visibility = visibility,
        tags = kwargs.get("tags"),
    )

coco_fmt_test = macro(
    doc = """Create a Coco format-check test plus a companion formatter binary.

Two targets are created:

- `<name>`: a test (run via `bazel test`) that fails if the package's Coco
  sources are not correctly formatted (runs `popili format --verify`).
- `<name>.format`: a binary (run via `bazel run`) that formats the sources in
  place (runs `popili format`).

To skip the test for specific packages, use standard Bazel tags, e.g.
`tags = ["manual"]`.""",
    inherit_attrs = _coco_fmt_test,
    attrs = {
        "package": attr.label(
            providers = [CocoPackageInfo],
            mandatory = True,
            configurable = False,
            doc = "The coco_package target to check/format.",
        ),
    },
    implementation = _coco_fmt_test_macro_impl,
)
