# DO NOT EDIT THIS FILE BY HAND. Instead run:
#   //tools:update_digests

"""Maps version aliases (like "stable") to actual version numbers."""

VERSION_ALIASES = {
    "stable": "1.5.3",
    "testing": "1.5.3",
}
