workspace(name = "rules_coco_cc_runtime_extra_deps_test")

load("@bazel_tools//tools/build_defs/repo:local.bzl", "local_repository")

local_repository(
    name = "rules_coco",
    path = "../..",
)

load("@rules_coco//coco:repositories.bzl", "coco_repositories")

coco_repositories(
    cc = True,
    cc_runtime_extra_deps = ["@rules_coco_cc_runtime_extra_deps_test//stub:boost_stub"],
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "googletest",
    sha256 = "da82b18757e7c55a0965cb1754040b7135b669e1f2db7d8babe78dfb6ce0d243",
    strip_prefix = "googletest-f840327b0f76408eafde2440af3b2f0a70662ea6",
    urls = ["https://github.com/google/googletest/archive/f840327b0f76408eafde2440af3b2f0a70662ea6.zip"],
)
