workspace(name = "rules_coco_cc_runtime_extra_deps_test")

load("@bazel_tools//tools/build_defs/repo:local.bzl", "local_repository")

local_repository(
    name = "rules_coco",
    path = "../..",
)

load("@rules_coco//coco:repositories.bzl", "coco_repositories")

coco_repositories(
    cc = True,
    cc_runtime_extra_deps = ["@rules_coco_cc_runtime_extra_deps_test//stub:boost_stub"],
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "googletest",
    sha256 = "b4916454ac39744bea81f8365a8ae43bc21d9da222cb7b2c01ee71d6ce09a033",
    strip_prefix = "googletest-7140cd416cecd7462a8aae488024abeee55598e4",
    urls = ["https://github.com/google/googletest/archive/7140cd416cecd7462a8aae488024abeee55598e4.zip"],
)
