workspace(name = "rules_coco_cc_runtime_extra_deps_test")

load("@bazel_tools//tools/build_defs/repo:local.bzl", "local_repository")

local_repository(
    name = "rules_coco",
    path = "../..",
)

load("@rules_coco//coco:repositories.bzl", "coco_repositories")

coco_repositories(
    cc = True,
    cc_runtime_extra_deps = ["@rules_coco_cc_runtime_extra_deps_test//stub:boost_stub"],
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "googletest",
    sha256 = "a4cb11930215b071168811982dfbebc82a2bb0f90db0e8713245931eb742ea46",
    strip_prefix = "googletest-d72f9c8aea6817cdf1ca0ac10887f328de7f3da2",
    urls = ["https://github.com/google/googletest/archive/d72f9c8aea6817cdf1ca0ac10887f328de7f3da2.zip"],
)
