# E2E smoke test WORKSPACE for testing rules_coco in WORKSPACE mode

workspace(name = "rules_coco_smoke_test")

load("@bazel_tools//tools/build_defs/repo:local.bzl", "local_repository")

# Use local development version of rules_coco
local_repository(
    name = "rules_coco",
    path = "../..",
)

load("@rules_coco//coco:repositories.bzl", "coco_repositories")

# Register coco toolchain with default stable version
coco_repositories(
    cc = True,
)

# Load GoogleTest for C++ unit tests
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "googletest",
    sha256 = "d5b5c2f75be09fa81619166ef6e033b9caba659075bd07e3493241f667ccb1ca",
    strip_prefix = "googletest-1b96fa13f549387b7549cc89e1a785cf143a1a50",
    urls = ["https://github.com/google/googletest/archive/1b96fa13f549387b7549cc89e1a785cf143a1a50.zip"],
)
