# E2E smoke test WORKSPACE for testing rules_coco in WORKSPACE mode

workspace(name = "rules_coco_smoke_test")

load("@bazel_tools//tools/build_defs/repo:local.bzl", "local_repository")

# Use local development version of rules_coco
local_repository(
    name = "rules_coco",
    path = "../..",
)

load("@rules_coco//coco:repositories.bzl", "coco_repositories")

# Register coco toolchain with default stable version
coco_repositories(
    cc = True,
)

# Load GoogleTest for C++ unit tests
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "googletest",
    sha256 = "44309ac4e6735f7d59999f38ff709cafce7230639591bbf8573b5e1e06310d64",
    strip_prefix = "googletest-283c17563fe7a1111cd7f581aa5d541e8baeff2f",
    urls = ["https://github.com/google/googletest/archive/283c17563fe7a1111cd7f581aa5d541e8baeff2f.zip"],
)
