#!/usr/bin/env python3

# Copyright 2023 Cocotec Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import json
from pathlib import Path
from typing import Dict
from urllib.error import HTTPError
from urllib.request import urlopen

tools_dir = Path(__file__).resolve().parent


def read_url(url: str) -> str:
    return urlopen(url).read().decode('utf-8')


def download_sha_file(url: str) -> Dict[str, str]:
    result: Dict[str, str] = {}
    for line in read_url(url).splitlines():
        sha, file = line.split(' ')
        result[file] = sha
    return result


def create_digest_dictionary(versions_file: str) -> Dict[str, str]:
    result: Dict[str, str] = {}
    for version in json.loads(versions_file)["all"]:
        try:
            for file, digest in download_sha_file(
                    f'https://dl.cocotec.io/cp/archive/{version}/sha256sums.txt'
            ).items():
                result[f'{version}/{file}'] = digest
        except HTTPError:
            pass
    return result


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--versions",
                        action="store",
                        type=str,
                        default="https://dl.cocotec.io/cp/versions.json")
    parser.add_argument("--out",
                        action="store",
                        type=Path,
                        default=tools_dir.parent / "coco" / "known_shas.bzl")

    options = parser.parse_args()

    digests = create_digest_dictionary(read_url(options.versions))
    with open(options.out, 'w') as f:
        f.write(f"""# DO NOT EDIT THIS FILE BY HAND. Instead run:
#   //tools:update_digests
FILE_KEY_TO_SHA = {json.dumps(digests, indent=4)}
""")
